# Automatically generated by configure - do not modify!
shared=no
build_suffix=
prefix=./Build/vs15/x64-static
libdir=${prefix}/lib
incdir=${prefix}/include
rpath=
source_path=.
LIBPREF=lib
LIBSUF=.a
extralibs_avutil="user32.lib
bcrypt.lib"
extralibs_avcodec="ole32.lib
user32.lib"
extralibs_avformat="secur32.lib
ws2_32.lib"
extralibs_avdevice="psapi.lib
ole32.lib
strmiids.lib
uuid.lib
oleaut32.lib
shlwapi.lib
gdi32.lib
vfw32.lib"
extralibs_avfilter=""
extralibs_avresample=""
extralibs_postproc=""
extralibs_swscale=""
extralibs_swresample=""
avcodec_deps="swresample avutil"
avdevice_deps="avfilter swscale avformat avcodec swresample avutil"
avfilter_deps="swscale avformat avcodec swresample avutil"
avformat_deps="avcodec swresample avutil"
avresample_deps="avutil"
avutil_deps=""
postproc_deps="avutil"
swresample_deps="avutil"
swscale_deps="avutil"
